// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-eorNg87Ku0sL7ePTLNGd4onrxadXfdQ',
    appId: '1:863701601139:web:5cce4c2db7f973db5e1306',
    messagingSenderId: '863701601139',
    projectId: 'festive-cure-care',
    authDomain: 'festive-cure-care.firebaseapp.com',
    storageBucket: 'festive-cure-care.firebasestorage.app',
    measurementId: 'G-R941TCE6TD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ1IjGbEaQCrXUI0RK-eV38oi5p7j0AO4',
    appId: '1:863701601139:android:cb2534265d27d8b55e1306',
    messagingSenderId: '863701601139',
    projectId: 'festive-cure-care',
    storageBucket: 'festive-cure-care.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD9vTu3XIhH-a-KjcVPYQUX5yw24QeXlQ',
    appId: '1:863701601139:ios:6ea791cba82924c65e1306',
    messagingSenderId: '863701601139',
    projectId: 'festive-cure-care',
    storageBucket: 'festive-cure-care.firebasestorage.app',
    androidClientId: '863701601139-8sv8n5el4531fce2mbnj48sf7ekgk0je.apps.googleusercontent.com',
    iosClientId: '863701601139-lqved54hdqfvtq4hh8lchcb8vknpl7df.apps.googleusercontent.com',
    iosBundleId: 'com.example.festiveCareCure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD9vTu3XIhH-a-KjcVPYQUX5yw24QeXlQ',
    appId: '1:863701601139:ios:6ea791cba82924c65e1306',
    messagingSenderId: '863701601139',
    projectId: 'festive-cure-care',
    storageBucket: 'festive-cure-care.firebasestorage.app',
    androidClientId: '863701601139-8sv8n5el4531fce2mbnj48sf7ekgk0je.apps.googleusercontent.com',
    iosClientId: '863701601139-lqved54hdqfvtq4hh8lchcb8vknpl7df.apps.googleusercontent.com',
    iosBundleId: 'com.example.festiveCareCure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-eorNg87Ku0sL7ePTLNGd4onrxadXfdQ',
    appId: '1:863701601139:web:ac5f5454d9d0fd325e1306',
    messagingSenderId: '863701601139',
    projectId: 'festive-cure-care',
    authDomain: 'festive-cure-care.firebaseapp.com',
    storageBucket: 'festive-cure-care.firebasestorage.app',
    measurementId: 'G-2E7SJ8MT02',
  );

}